#!/usr/bin/env bash

if [[ $# -ne 1 ]] ; then
    echo 'Usage: ./setup.sh INSTANCE_NAME'
    exit 1
fi

if [[ "$1" = "uat" ]] || [[ "$1" = "science" ]] || [[ "$1" = "production" ]] ; then
    echo $1 > instance
else
    echo 'INSTANCE_NAME must be one of [uat, science, production]'
    exit 1
fi
