vault:
  ## Address of the vault server.  This should be a string if it is
  ## present.
  addr: https://vault.dide.ic.ac.uk:8200
  auth:
    ## Authentication type - must be either "token" or the name of a
    ## supported authentication method.  These seem to be poorly
    ## documented in the hvac, but include "github" for github
    ## authentication.
    ##
    ## On a vault client object, see auth.implemented_class_names for
    ## a list, which is currently
    ##
    ##     azure, github, gcp, kubernetes, ldap, mfa, okta
    method: github

## Prefix for container names; we'll use {container_prefix}_(orderly,web)
##
## This is an important configuration option because it cannot be
## overridden by a patch file or by passing options in.
##
## IMPORTANT: If you want to change the prefix, you should stop
## OrderlyWeb, then change the prefix, then start it back up.
## Otherwise OrderlyWeb will not take down the required containers
## before starting back up.
container_prefix: orderly-web

## The name of the docker network that containers will be attached to.
## If you want to proxy OrderlyWeb to the host, you will need to
## arrange a proxy on this network, or use dev_mode in the web section
## below.
network: montagu_default

## Names of the docker volumes to use:
##
## orderly: stores the orderly archive
## proxy_logs: stores logs from the reverse proxy (only used if proxy is given)
## css: stores compiled css for the web app (only needed if custom sass variables
## are given as sass_variables in web section below)
##
## (More volumes are anticipated as the tool develops)
volumes:
  orderly: montagu_orderly_volume
  proxy_logs: orderly_web_proxy_logs
  css: orderly_web_css
  documents: montagu_documents
  redis: orderly_web_redis_data
  outpack: orderly_web_outpack

outpack:
  repo: mrcide
  migrate:
    name: outpack.orderly
    tag: main
  server:
    name: outpack_server
    tag: main

packit:
  repo: mrcide
  api:
    name: packit-api
    tag: main
  app:
    name: packit
    tag: main
  db:
    name: packit-db
    tag: main

## Redis configuration
redis:
  image:
    name: redis
    tag: "5.0"
  volume: orderly_web_redis_data

## Orderly configuration
orderly:
  ## Image to use for orderly.  This should build off of
  ## vimc/orderly.server but can be extended to use whatever packages
  ## you need.  The components repo, image and tag will be assembled as
  ## <repo>/<name>:<tag> for the full docker image reference.
  image:
    repo: vimc
    name: montagu-orderly
    tag: master
    worker_name: montagu-orderly
  env:
    SLACK_URL: VAULT:secret/vimc/slack/orderly-webhook:url
    TEAMS_URL: VAULT:secret/vimc/teams/orderly-webhook:url
    # These are set to nonsense values until VIMC-3547 is fixed as they
    # are required for the slack hook to work
    MONTAGU_PORTAL_USERNAME: unused
    MONTAGU_PORTAL_PASSWORD: unused
  ssh:
    public: VAULT:secret/vimc/reports/deploy:public
    private: VAULT:secret/vimc/reports/deploy:private
  workers: 1

## Api and Website configuration
web:
  ## Image to use for the web components.  As for the orderly
  ## configuration these will be assembled as <repo>/<name>:<tag>.  In
  ## addition, a second image with the database migration support will
  ## be used as <repo>/<migrate>:<tag>. It is not expected (unlike
  ## the orderly image) that the 'name' and 'migrate' will need to be
  ## changed often, and it is expected that a web image will go
  ## together with corresponding migration and admin images. If custom sass
  ## variables are provided below as sass_variables, a third image
  ## for generating css is required.
  image:
    repo: vimc
    name: orderly-web
    tag: master
    migrate: orderlyweb-migrate
    admin: orderly-web-user-cli
    css-generator: orderly-web-css-generator
  ## Public-facing url for the whole web service, including protocol
  ## (ideally https://), hostname and port (if not using standard
  ## ports).  Here, we're going to use the same as for the proxy but
  ## if you are using an external proxy then you'd use its hostname
  ## and port.
  url: https://localhost
  ## If dev_mode is true then the port is exposed to the host (as
  ## plain http).  Do not use in production.  The port is attached
  ## only to the localhost and will not be available from other
  ## machines
  dev_mode: false
  ## Port to use for the web service
  port: 8888
  ## Name of the web service (affects the UI)
  name: Reporting Portal
  ## Email address of the web service
  email: montagu-help@imperial.ac.uk
  ## Authentication configuration
  auth:
    ## Enable or disable fine grained permissions
    fine_grained: true
    ## Enable montagu authentication provider
    montagu: true
  ## Optional sass variables to override default styles. Should be a
  ## file path relative to the config file
  sass_variables: variables.scss
  ## Optional custom logo image, any valid image format. Should be a
  ## file path relative to the config file.
  logo: logo-green.png
  favicon: logo-small.png

slack:
  webhook_url: VAULT:secret/vimc/slack/orderly-deploy-webhook:url
