web:
  ## public url of the web service:
  url: https://production2.montagy.dide.ic.ac.uk/reports
  auth:
    montagu_url: https://production2.montagu.dide.ic.ac.uk
    montagu_api_url: https://production2.montagu.dide.ic.ac.uk/api/v1/
orderly:
  ## Environment variables that will be made available to orderly.
  ## Typically these will be in SHOUTY_SNAKE_CASE.  To pull values
  ## from the vault, use the format VAULT:<path>:<key>
  env:
    MONTAGU_DB_DEFAULT_INSTANCE: production
    MONTAGU_DB_PASSWORD_PRODUCTION: VAULT:secret/vimc/database/production/users/readonly:password
    ORDERLY_API_SERVER_IDENTITY: production
    ANNEX_HOST: annex.montagu.dide.ic.ac.uk
    ANNEX_PORT: 15432
    ANNEX_PASSWORD: VAULT:secret/vimc/annex/users/readonly:password
    VERSE_DEPLOY_KEY: VAULT:secret/vimc/verse/deploy:private
