web:
  image:
    repo: vimc
  ## public url of the web service:
  url: https://support.montagu.dide.ic.ac.uk:11443/reports
  auth:
    montagu_url: https://support.montagu.dide.ic.ac.uk:11443
    montagu_api_url: https://support.montagu.dide.ic.ac.uk:11443/api/v1/
orderly:
  ## Environment variables that will be made available to orderly.
  ## Typically these will be in SHOUTY_SNAKE_CASE.  To pull values
  ## from the vault, use the format VAULT:<path>:<key>
  env:
    MONTAGU_DB_DEFAULT_INSTANCE: science
    MONTAGU_DB_PASSWORD_SCIENCE: VAULT:secret/database/science/users/readonly:password
    ORDERLY_API_SERVER_IDENTITY: science
    ANNEX_HOST: annex.montagu.dide.ic.ac.uk
    ANNEX_PORT: 15432
    ANNEX_PASSWORD: VAULT:secret/annex/users/readonly:password
