web:
  image:
    repo: docker.montagu.dide.ic.ac.uk:5000 # use our local registry for testing
  ## public url of the web service:
  url: https://support.montagu.dide.ic.ac.uk:10443/reports
  auth:
    montagu_url: https://support.montagu.dide.ic.ac.uk:10443
    montagu_api_url: https://support.montagu.dide.ic.ac.uk:10443/api/v1/
orderly:
  ## Environment variables that will be made available to orderly.
  ## Typically these will be in SHOUTY_SNAKE_CASE.  To pull values
  ## from the vault, use the format VAULT:<path>:<key>
  env:
    MONTAGU_DB_DEFAULT_INSTANCE: uat
    MONTAGU_DB_PASSWORD_UAT: readonly
    ORDERLY_API_SERVER_IDENTITY: uat
    ANNEX_HOST: annex.montagu.dide.ic.ac.uk
    ANNEX_PORT: 15432
    ANNEX_PASSWORD: VAULT:secret/annex/users/readonly:password
