web:
  ## public url of the web service:
  url: https://support.dide.ic.ac.uk:10443/reports
  auth:
    montagu_url: https://support.montagu.dide.ic.ac.uk:10443
    montagu_api_url: https://support.montagu.dide.ic.ac.uk:10443/api/v1/
orderly:
  ## Environment variables that will be made available to orderly.
  ## Typically these will be in SHOUTY_SNAKE_CASE.  To pull values
  ## from the vault, use the format VAULT:<path>:<key>
  env:
    MONTAGU_PASSWORD: orderly
    ORDERLY_API_SERVER_IDENTITY: uat
    ANNEX_HOST: db_annex
    ANNEX_PORT: 5432
    ANNEX_PASSWORD: readonly
